/*
 * generated by Xtext 2.37.0
 */
package qcm.dsl.formatting2

import com.google.inject.Inject
import org.eclipse.xtext.formatting2.AbstractFormatter2
import org.eclipse.xtext.formatting2.IFormattableDocument
import qcm.Question
import qcm.Questionnaire
import qcm.dsl.services.DSLGrammarAccess

class DSLFormatter extends AbstractFormatter2 {
	
	@Inject extension DSLGrammarAccess

	def dispatch void format(Questionnaire questionnaire, extension IFormattableDocument document) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		for (question : questionnaire.possede) {
			question.format
		}
	}

	def dispatch void format(Question question, extension IFormattableDocument document) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		for (reponse : question.reponses) {
			reponse.format
		}
		for (etiquette : question.etiquette) {
			etiquette.format
		}
	}
	
}
