/*
 * generated by Xtext 2.37.0
 */
package qcm.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDSLScopeProvider extends DelegatingScopeProvider {
}
