/*
 * generated by Xtext 2.37.0
 */
package qcm.dsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import qcm.dsl.ide.contentassist.antlr.internal.InternalDSLParser;
import qcm.dsl.services.DSLGrammarAccess;

public class DSLParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(DSLGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, DSLGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
			builder.put(grammarAccess.getQuestionnaireAccess().getGroup(), "rule__Questionnaire__Group__0");
			builder.put(grammarAccess.getQuestionnaireAccess().getGroup_5(), "rule__Questionnaire__Group_5__0");
			builder.put(grammarAccess.getQuestionnaireAccess().getGroup_9(), "rule__Questionnaire__Group_9__0");
			builder.put(grammarAccess.getQuestionAccess().getGroup(), "rule__Question__Group__0");
			builder.put(grammarAccess.getQuestionAccess().getGroup_7(), "rule__Question__Group_7__0");
			builder.put(grammarAccess.getQuestionAccess().getGroup_11(), "rule__Question__Group_11__0");
			builder.put(grammarAccess.getQuestionAccess().getGroup_13(), "rule__Question__Group_13__0");
			builder.put(grammarAccess.getQuestionAccess().getGroup_13_3(), "rule__Question__Group_13_3__0");
			builder.put(grammarAccess.getELongAccess().getGroup(), "rule__ELong__Group__0");
			builder.put(grammarAccess.getReponseAccess().getGroup(), "rule__Reponse__Group__0");
			builder.put(grammarAccess.getEtiquetteAccess().getGroup(), "rule__Etiquette__Group__0");
			builder.put(grammarAccess.getEtiquetteAccess().getGroup_4(), "rule__Etiquette__Group_4__0");
			builder.put(grammarAccess.getQuestionnaireAccess().getMelangeAssignment_0(), "rule__Questionnaire__MelangeAssignment_0");
			builder.put(grammarAccess.getQuestionnaireAccess().getTitreAssignment_4(), "rule__Questionnaire__TitreAssignment_4");
			builder.put(grammarAccess.getQuestionnaireAccess().getRetourArriereAssignment_5_1(), "rule__Questionnaire__RetourArriereAssignment_5_1");
			builder.put(grammarAccess.getQuestionnaireAccess().getPossedeAssignment_8(), "rule__Questionnaire__PossedeAssignment_8");
			builder.put(grammarAccess.getQuestionnaireAccess().getPossedeAssignment_9_1(), "rule__Questionnaire__PossedeAssignment_9_1");
			builder.put(grammarAccess.getQuestionAccess().getReponseUniqueAssignment_0(), "rule__Question__ReponseUniqueAssignment_0");
			builder.put(grammarAccess.getQuestionAccess().getIntituleAssignment_4(), "rule__Question__IntituleAssignment_4");
			builder.put(grammarAccess.getQuestionAccess().getDifficulteAssignment_6(), "rule__Question__DifficulteAssignment_6");
			builder.put(grammarAccess.getQuestionAccess().getQuestionSuivanteAssignment_7_1(), "rule__Question__QuestionSuivanteAssignment_7_1");
			builder.put(grammarAccess.getQuestionAccess().getReponsesAssignment_10(), "rule__Question__ReponsesAssignment_10");
			builder.put(grammarAccess.getQuestionAccess().getReponsesAssignment_11_1(), "rule__Question__ReponsesAssignment_11_1");
			builder.put(grammarAccess.getQuestionAccess().getEtiquetteAssignment_13_2(), "rule__Question__EtiquetteAssignment_13_2");
			builder.put(grammarAccess.getQuestionAccess().getEtiquetteAssignment_13_3_1(), "rule__Question__EtiquetteAssignment_13_3_1");
			builder.put(grammarAccess.getReponseAccess().getValideAssignment_0(), "rule__Reponse__ValideAssignment_0");
			builder.put(grammarAccess.getReponseAccess().getIntituleAssignment_4(), "rule__Reponse__IntituleAssignment_4");
			builder.put(grammarAccess.getEtiquetteAccess().getCategorieAssignment_3(), "rule__Etiquette__CategorieAssignment_3");
			builder.put(grammarAccess.getEtiquetteAccess().getSousEtiquetteAssignment_4_1(), "rule__Etiquette__SousEtiquetteAssignment_4_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private DSLGrammarAccess grammarAccess;

	@Override
	protected InternalDSLParser createParser() {
		InternalDSLParser result = new InternalDSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public DSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
