/*
 * generated by Xtext 2.37.0
 */
package qcm.dsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class DSLGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class QuestionnaireElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "qcm.dsl.DSL.Questionnaire");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cMelangeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cMelangeMelangeKeyword_0_0 = (Keyword)cMelangeAssignment_0.eContents().get(0);
		private final Keyword cQuestionnaireKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cTitreKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTitreAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTitreEStringParserRuleCall_4_0 = (RuleCall)cTitreAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cRetourArriereKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cRetourArriereAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cRetourArriereEBooleanParserRuleCall_5_1_0 = (RuleCall)cRetourArriereAssignment_5_1.eContents().get(0);
		private final Keyword cPossedeKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cLeftCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cPossedeAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cPossedeQuestionParserRuleCall_8_0 = (RuleCall)cPossedeAssignment_8.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cCommaKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cPossedeAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cPossedeQuestionParserRuleCall_9_1_0 = (RuleCall)cPossedeAssignment_9_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//Questionnaire returns Questionnaire:
		//    (melange?='melange')?
		//    'Questionnaire'
		//    '{'
		//        'titre' titre=EString
		//        ('retourArriere' retourArriere=EBoolean)?
		//        'possede' '{' possede+=Question ( "," possede+=Question)* '}'
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//(melange?='melange')?
		//'Questionnaire'
		//'{'
		//    'titre' titre=EString
		//    ('retourArriere' retourArriere=EBoolean)?
		//    'possede' '{' possede+=Question ( "," possede+=Question)* '}'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//(melange?='melange')?
		public Assignment getMelangeAssignment_0() { return cMelangeAssignment_0; }
		
		//'melange'
		public Keyword getMelangeMelangeKeyword_0_0() { return cMelangeMelangeKeyword_0_0; }
		
		//'Questionnaire'
		public Keyword getQuestionnaireKeyword_1() { return cQuestionnaireKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'titre'
		public Keyword getTitreKeyword_3() { return cTitreKeyword_3; }
		
		//titre=EString
		public Assignment getTitreAssignment_4() { return cTitreAssignment_4; }
		
		//EString
		public RuleCall getTitreEStringParserRuleCall_4_0() { return cTitreEStringParserRuleCall_4_0; }
		
		//('retourArriere' retourArriere=EBoolean)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'retourArriere'
		public Keyword getRetourArriereKeyword_5_0() { return cRetourArriereKeyword_5_0; }
		
		//retourArriere=EBoolean
		public Assignment getRetourArriereAssignment_5_1() { return cRetourArriereAssignment_5_1; }
		
		//EBoolean
		public RuleCall getRetourArriereEBooleanParserRuleCall_5_1_0() { return cRetourArriereEBooleanParserRuleCall_5_1_0; }
		
		//'possede'
		public Keyword getPossedeKeyword_6() { return cPossedeKeyword_6; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7() { return cLeftCurlyBracketKeyword_7; }
		
		//possede+=Question
		public Assignment getPossedeAssignment_8() { return cPossedeAssignment_8; }
		
		//Question
		public RuleCall getPossedeQuestionParserRuleCall_8_0() { return cPossedeQuestionParserRuleCall_8_0; }
		
		//( "," possede+=Question)*
		public Group getGroup_9() { return cGroup_9; }
		
		//","
		public Keyword getCommaKeyword_9_0() { return cCommaKeyword_9_0; }
		
		//possede+=Question
		public Assignment getPossedeAssignment_9_1() { return cPossedeAssignment_9_1; }
		
		//Question
		public RuleCall getPossedeQuestionParserRuleCall_9_1_0() { return cPossedeQuestionParserRuleCall_9_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "qcm.dsl.DSL.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "qcm.dsl.DSL.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean returns ecore::EBoolean:
		//    'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	public class QuestionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "qcm.dsl.DSL.Question");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cReponseUniqueAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cReponseUniqueReponseUniqueKeyword_0_0 = (Keyword)cReponseUniqueAssignment_0.eContents().get(0);
		private final Keyword cQuestionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cIntituleKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cIntituleAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cIntituleEStringParserRuleCall_4_0 = (RuleCall)cIntituleAssignment_4.eContents().get(0);
		private final Keyword cDifficulteKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cDifficulteAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cDifficulteELongParserRuleCall_6_0 = (RuleCall)cDifficulteAssignment_6.eContents().get(0);
		private final Keyword cReponsesKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cLeftCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cReponsesAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cReponsesReponseParserRuleCall_9_0 = (RuleCall)cReponsesAssignment_9.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cCommaKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cReponsesAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cReponsesReponseParserRuleCall_10_1_0 = (RuleCall)cReponsesAssignment_10_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cEtiquetteKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_12_1 = (Keyword)cGroup_12.eContents().get(1);
		private final Assignment cEtiquetteAssignment_12_2 = (Assignment)cGroup_12.eContents().get(2);
		private final RuleCall cEtiquetteEtiquetteParserRuleCall_12_2_0 = (RuleCall)cEtiquetteAssignment_12_2.eContents().get(0);
		private final Group cGroup_12_3 = (Group)cGroup_12.eContents().get(3);
		private final Keyword cCommaKeyword_12_3_0 = (Keyword)cGroup_12_3.eContents().get(0);
		private final Assignment cEtiquetteAssignment_12_3_1 = (Assignment)cGroup_12_3.eContents().get(1);
		private final RuleCall cEtiquetteEtiquetteParserRuleCall_12_3_1_0 = (RuleCall)cEtiquetteAssignment_12_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_12_4 = (Keyword)cGroup_12.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		
		//Question returns Question:
		//    reponseUnique?='reponseUnique'
		//    'Question'
		//    '{'
		//        'intitule' intitule=EString
		//        'difficulte' difficulte=ELong
		//        'reponses' '{' reponses+=Reponse ( "," reponses+=Reponse)* '}'
		//        ('etiquette' '{' etiquette+=Etiquette ( "," etiquette+=Etiquette)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//reponseUnique?='reponseUnique'
		//'Question'
		//'{'
		//    'intitule' intitule=EString
		//    'difficulte' difficulte=ELong
		//    'reponses' '{' reponses+=Reponse ( "," reponses+=Reponse)* '}'
		//    ('etiquette' '{' etiquette+=Etiquette ( "," etiquette+=Etiquette)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//reponseUnique?='reponseUnique'
		public Assignment getReponseUniqueAssignment_0() { return cReponseUniqueAssignment_0; }
		
		//'reponseUnique'
		public Keyword getReponseUniqueReponseUniqueKeyword_0_0() { return cReponseUniqueReponseUniqueKeyword_0_0; }
		
		//'Question'
		public Keyword getQuestionKeyword_1() { return cQuestionKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'intitule'
		public Keyword getIntituleKeyword_3() { return cIntituleKeyword_3; }
		
		//intitule=EString
		public Assignment getIntituleAssignment_4() { return cIntituleAssignment_4; }
		
		//EString
		public RuleCall getIntituleEStringParserRuleCall_4_0() { return cIntituleEStringParserRuleCall_4_0; }
		
		//'difficulte'
		public Keyword getDifficulteKeyword_5() { return cDifficulteKeyword_5; }
		
		//difficulte=ELong
		public Assignment getDifficulteAssignment_6() { return cDifficulteAssignment_6; }
		
		//ELong
		public RuleCall getDifficulteELongParserRuleCall_6_0() { return cDifficulteELongParserRuleCall_6_0; }
		
		//'reponses'
		public Keyword getReponsesKeyword_7() { return cReponsesKeyword_7; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_8() { return cLeftCurlyBracketKeyword_8; }
		
		//reponses+=Reponse
		public Assignment getReponsesAssignment_9() { return cReponsesAssignment_9; }
		
		//Reponse
		public RuleCall getReponsesReponseParserRuleCall_9_0() { return cReponsesReponseParserRuleCall_9_0; }
		
		//( "," reponses+=Reponse)*
		public Group getGroup_10() { return cGroup_10; }
		
		//","
		public Keyword getCommaKeyword_10_0() { return cCommaKeyword_10_0; }
		
		//reponses+=Reponse
		public Assignment getReponsesAssignment_10_1() { return cReponsesAssignment_10_1; }
		
		//Reponse
		public RuleCall getReponsesReponseParserRuleCall_10_1_0() { return cReponsesReponseParserRuleCall_10_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
		
		//('etiquette' '{' etiquette+=Etiquette ( "," etiquette+=Etiquette)* '}' )?
		public Group getGroup_12() { return cGroup_12; }
		
		//'etiquette'
		public Keyword getEtiquetteKeyword_12_0() { return cEtiquetteKeyword_12_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_12_1() { return cLeftCurlyBracketKeyword_12_1; }
		
		//etiquette+=Etiquette
		public Assignment getEtiquetteAssignment_12_2() { return cEtiquetteAssignment_12_2; }
		
		//Etiquette
		public RuleCall getEtiquetteEtiquetteParserRuleCall_12_2_0() { return cEtiquetteEtiquetteParserRuleCall_12_2_0; }
		
		//( "," etiquette+=Etiquette)*
		public Group getGroup_12_3() { return cGroup_12_3; }
		
		//","
		public Keyword getCommaKeyword_12_3_0() { return cCommaKeyword_12_3_0; }
		
		//etiquette+=Etiquette
		public Assignment getEtiquetteAssignment_12_3_1() { return cEtiquetteAssignment_12_3_1; }
		
		//Etiquette
		public RuleCall getEtiquetteEtiquetteParserRuleCall_12_3_1_0() { return cEtiquetteEtiquetteParserRuleCall_12_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_12_4() { return cRightCurlyBracketKeyword_12_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }
	}
	public class ELongElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "qcm.dsl.DSL.ELong");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//ELong returns ecore::ELong:
		//    '-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class ReponseElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "qcm.dsl.DSL.Reponse");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cValideAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cValideValideKeyword_0_0 = (Keyword)cValideAssignment_0.eContents().get(0);
		private final Keyword cReponseKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cIntituleKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cIntituleAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cIntituleEStringParserRuleCall_4_0 = (RuleCall)cIntituleAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Reponse returns Reponse:
		//    (valide?='valide')?
		//    'Reponse'
		//    '{'
		//        'intitule' intitule=EString
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//(valide?='valide')?
		//'Reponse'
		//'{'
		//    'intitule' intitule=EString
		//'}'
		public Group getGroup() { return cGroup; }
		
		//(valide?='valide')?
		public Assignment getValideAssignment_0() { return cValideAssignment_0; }
		
		//'valide'
		public Keyword getValideValideKeyword_0_0() { return cValideValideKeyword_0_0; }
		
		//'Reponse'
		public Keyword getReponseKeyword_1() { return cReponseKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'intitule'
		public Keyword getIntituleKeyword_3() { return cIntituleKeyword_3; }
		
		//intitule=EString
		public Assignment getIntituleAssignment_4() { return cIntituleAssignment_4; }
		
		//EString
		public RuleCall getIntituleEStringParserRuleCall_4_0() { return cIntituleEStringParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class EtiquetteElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "qcm.dsl.DSL.Etiquette");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEtiquetteKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cCategorieKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cCategorieAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cCategorieEStringParserRuleCall_3_0 = (RuleCall)cCategorieAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cSousEtiquetteKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cSousEtiquetteAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cSousEtiquetteEtiquetteCrossReference_4_1_0 = (CrossReference)cSousEtiquetteAssignment_4_1.eContents().get(0);
		private final RuleCall cSousEtiquetteEtiquetteEStringParserRuleCall_4_1_0_1 = (RuleCall)cSousEtiquetteEtiquetteCrossReference_4_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Etiquette returns Etiquette:
		//    'Etiquette'
		//    '{'
		//        'categorie' categorie=EString
		//        ('sousEtiquette' sousEtiquette=[Etiquette|EString])?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Etiquette'
		//'{'
		//    'categorie' categorie=EString
		//    ('sousEtiquette' sousEtiquette=[Etiquette|EString])?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Etiquette'
		public Keyword getEtiquetteKeyword_0() { return cEtiquetteKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'categorie'
		public Keyword getCategorieKeyword_2() { return cCategorieKeyword_2; }
		
		//categorie=EString
		public Assignment getCategorieAssignment_3() { return cCategorieAssignment_3; }
		
		//EString
		public RuleCall getCategorieEStringParserRuleCall_3_0() { return cCategorieEStringParserRuleCall_3_0; }
		
		//('sousEtiquette' sousEtiquette=[Etiquette|EString])?
		public Group getGroup_4() { return cGroup_4; }
		
		//'sousEtiquette'
		public Keyword getSousEtiquetteKeyword_4_0() { return cSousEtiquetteKeyword_4_0; }
		
		//sousEtiquette=[Etiquette|EString]
		public Assignment getSousEtiquetteAssignment_4_1() { return cSousEtiquetteAssignment_4_1; }
		
		//[Etiquette|EString]
		public CrossReference getSousEtiquetteEtiquetteCrossReference_4_1_0() { return cSousEtiquetteEtiquetteCrossReference_4_1_0; }
		
		//EString
		public RuleCall getSousEtiquetteEtiquetteEStringParserRuleCall_4_1_0_1() { return cSousEtiquetteEtiquetteEStringParserRuleCall_4_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	
	
	private final QuestionnaireElements pQuestionnaire;
	private final EStringElements pEString;
	private final EBooleanElements pEBoolean;
	private final QuestionElements pQuestion;
	private final ELongElements pELong;
	private final ReponseElements pReponse;
	private final EtiquetteElements pEtiquette;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public DSLGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pQuestionnaire = new QuestionnaireElements();
		this.pEString = new EStringElements();
		this.pEBoolean = new EBooleanElements();
		this.pQuestion = new QuestionElements();
		this.pELong = new ELongElements();
		this.pReponse = new ReponseElements();
		this.pEtiquette = new EtiquetteElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("qcm.dsl.DSL".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Questionnaire returns Questionnaire:
	//    (melange?='melange')?
	//    'Questionnaire'
	//    '{'
	//        'titre' titre=EString
	//        ('retourArriere' retourArriere=EBoolean)?
	//        'possede' '{' possede+=Question ( "," possede+=Question)* '}'
	//    '}';
	public QuestionnaireElements getQuestionnaireAccess() {
		return pQuestionnaire;
	}
	
	public ParserRule getQuestionnaireRule() {
		return getQuestionnaireAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//EBoolean returns ecore::EBoolean:
	//    'true' | 'false';
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//Question returns Question:
	//    reponseUnique?='reponseUnique'
	//    'Question'
	//    '{'
	//        'intitule' intitule=EString
	//        'difficulte' difficulte=ELong
	//        'reponses' '{' reponses+=Reponse ( "," reponses+=Reponse)* '}'
	//        ('etiquette' '{' etiquette+=Etiquette ( "," etiquette+=Etiquette)* '}' )?
	//    '}';
	public QuestionElements getQuestionAccess() {
		return pQuestion;
	}
	
	public ParserRule getQuestionRule() {
		return getQuestionAccess().getRule();
	}
	
	//ELong returns ecore::ELong:
	//    '-'? INT;
	public ELongElements getELongAccess() {
		return pELong;
	}
	
	public ParserRule getELongRule() {
		return getELongAccess().getRule();
	}
	
	//Reponse returns Reponse:
	//    (valide?='valide')?
	//    'Reponse'
	//    '{'
	//        'intitule' intitule=EString
	//    '}';
	public ReponseElements getReponseAccess() {
		return pReponse;
	}
	
	public ParserRule getReponseRule() {
		return getReponseAccess().getRule();
	}
	
	//Etiquette returns Etiquette:
	//    'Etiquette'
	//    '{'
	//        'categorie' categorie=EString
	//        ('sousEtiquette' sousEtiquette=[Etiquette|EString])?
	//    '}';
	public EtiquetteElements getEtiquetteAccess() {
		return pEtiquette;
	}
	
	public ParserRule getEtiquetteRule() {
		return getEtiquetteAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
