/*
 * generated by Xtext 2.37.0
 */
grammar InternalDSL;

options {
	superClass=AbstractInternalAntlrParser;
}

@lexer::header {
package qcm.dsl.parser.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.parser.antlr.Lexer;
}

@parser::header {
package qcm.dsl.parser.antlr.internal;

import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken;
import qcm.dsl.services.DSLGrammarAccess;

}

@parser::members {

 	private DSLGrammarAccess grammarAccess;

    public InternalDSLParser(TokenStream input, DSLGrammarAccess grammarAccess) {
        this(input);
        this.grammarAccess = grammarAccess;
        registerRules(grammarAccess.getGrammar());
    }

    @Override
    protected String getFirstRuleName() {
    	return "Questionnaire";
   	}

   	@Override
   	protected DSLGrammarAccess getGrammarAccess() {
   		return grammarAccess;
   	}

}

@rulecatch {
    catch (RecognitionException re) {
        recover(input,re);
        appendSkippedTokens();
    }
}

// Entry rule entryRuleQuestionnaire
entryRuleQuestionnaire returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getQuestionnaireRule()); }
	iv_ruleQuestionnaire=ruleQuestionnaire
	{ $current=$iv_ruleQuestionnaire.current; }
	EOF;

// Rule Questionnaire
ruleQuestionnaire returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				lv_melange_0_0='melange'
				{
					newLeafNode(lv_melange_0_0, grammarAccess.getQuestionnaireAccess().getMelangeMelangeKeyword_0_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getQuestionnaireRule());
					}
					setWithLastConsumed($current, "melange", lv_melange_0_0 != null, "melange");
				}
			)
		)?
		otherlv_1='Questionnaire'
		{
			newLeafNode(otherlv_1, grammarAccess.getQuestionnaireAccess().getQuestionnaireKeyword_1());
		}
		otherlv_2='{'
		{
			newLeafNode(otherlv_2, grammarAccess.getQuestionnaireAccess().getLeftCurlyBracketKeyword_2());
		}
		otherlv_3='titre'
		{
			newLeafNode(otherlv_3, grammarAccess.getQuestionnaireAccess().getTitreKeyword_3());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getQuestionnaireAccess().getTitreEStringParserRuleCall_4_0());
				}
				lv_titre_4_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getQuestionnaireRule());
					}
					set(
						$current,
						"titre",
						lv_titre_4_0,
						"qcm.dsl.DSL.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_5='retourArriere'
			{
				newLeafNode(otherlv_5, grammarAccess.getQuestionnaireAccess().getRetourArriereKeyword_5_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getQuestionnaireAccess().getRetourArriereEBooleanParserRuleCall_5_1_0());
					}
					lv_retourArriere_6_0=ruleEBoolean
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getQuestionnaireRule());
						}
						set(
							$current,
							"retourArriere",
							lv_retourArriere_6_0,
							"qcm.dsl.DSL.EBoolean");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		otherlv_7='possede'
		{
			newLeafNode(otherlv_7, grammarAccess.getQuestionnaireAccess().getPossedeKeyword_6());
		}
		otherlv_8='{'
		{
			newLeafNode(otherlv_8, grammarAccess.getQuestionnaireAccess().getLeftCurlyBracketKeyword_7());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getQuestionnaireAccess().getPossedeQuestionParserRuleCall_8_0());
				}
				lv_possede_9_0=ruleQuestion
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getQuestionnaireRule());
					}
					add(
						$current,
						"possede",
						lv_possede_9_0,
						"qcm.dsl.DSL.Question");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_10=','
			{
				newLeafNode(otherlv_10, grammarAccess.getQuestionnaireAccess().getCommaKeyword_9_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getQuestionnaireAccess().getPossedeQuestionParserRuleCall_9_1_0());
					}
					lv_possede_11_0=ruleQuestion
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getQuestionnaireRule());
						}
						add(
							$current,
							"possede",
							lv_possede_11_0,
							"qcm.dsl.DSL.Question");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)*
		otherlv_12='}'
		{
			newLeafNode(otherlv_12, grammarAccess.getQuestionnaireAccess().getRightCurlyBracketKeyword_10());
		}
		otherlv_13='}'
		{
			newLeafNode(otherlv_13, grammarAccess.getQuestionnaireAccess().getRightCurlyBracketKeyword_11());
		}
	)
;

// Entry rule entryRuleEString
entryRuleEString returns [String current=null]:
	{ newCompositeNode(grammarAccess.getEStringRule()); }
	iv_ruleEString=ruleEString
	{ $current=$iv_ruleEString.current.getText(); }
	EOF;

// Rule EString
ruleEString returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		this_STRING_0=RULE_STRING
		{
			$current.merge(this_STRING_0);
		}
		{
			newLeafNode(this_STRING_0, grammarAccess.getEStringAccess().getSTRINGTerminalRuleCall_0());
		}
		    |
		this_ID_1=RULE_ID
		{
			$current.merge(this_ID_1);
		}
		{
			newLeafNode(this_ID_1, grammarAccess.getEStringAccess().getIDTerminalRuleCall_1());
		}
	)
;

// Entry rule entryRuleEBoolean
entryRuleEBoolean returns [String current=null]:
	{ newCompositeNode(grammarAccess.getEBooleanRule()); }
	iv_ruleEBoolean=ruleEBoolean
	{ $current=$iv_ruleEBoolean.current.getText(); }
	EOF;

// Rule EBoolean
ruleEBoolean returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		kw='true'
		{
			$current.merge(kw);
			newLeafNode(kw, grammarAccess.getEBooleanAccess().getTrueKeyword_0());
		}
		    |
		kw='false'
		{
			$current.merge(kw);
			newLeafNode(kw, grammarAccess.getEBooleanAccess().getFalseKeyword_1());
		}
	)
;

// Entry rule entryRuleQuestion
entryRuleQuestion returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getQuestionRule()); }
	iv_ruleQuestion=ruleQuestion
	{ $current=$iv_ruleQuestion.current; }
	EOF;

// Rule Question
ruleQuestion returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='Question'
		{
			newLeafNode(otherlv_0, grammarAccess.getQuestionAccess().getQuestionKeyword_0());
		}
		otherlv_1='{'
		{
			newLeafNode(otherlv_1, grammarAccess.getQuestionAccess().getLeftCurlyBracketKeyword_1());
		}
		otherlv_2='intitule'
		{
			newLeafNode(otherlv_2, grammarAccess.getQuestionAccess().getIntituleKeyword_2());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getQuestionAccess().getIntituleEStringParserRuleCall_3_0());
				}
				lv_intitule_3_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getQuestionRule());
					}
					set(
						$current,
						"intitule",
						lv_intitule_3_0,
						"qcm.dsl.DSL.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_4='difficulte'
		{
			newLeafNode(otherlv_4, grammarAccess.getQuestionAccess().getDifficulteKeyword_4());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getQuestionAccess().getDifficulteELongParserRuleCall_5_0());
				}
				lv_difficulte_5_0=ruleELong
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getQuestionRule());
					}
					set(
						$current,
						"difficulte",
						lv_difficulte_5_0,
						"qcm.dsl.DSL.ELong");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_6='reponses'
		{
			newLeafNode(otherlv_6, grammarAccess.getQuestionAccess().getReponsesKeyword_6());
		}
		otherlv_7='{'
		{
			newLeafNode(otherlv_7, grammarAccess.getQuestionAccess().getLeftCurlyBracketKeyword_7());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getQuestionAccess().getReponsesReponseParserRuleCall_8_0());
				}
				lv_reponses_8_0=ruleReponse
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getQuestionRule());
					}
					add(
						$current,
						"reponses",
						lv_reponses_8_0,
						"qcm.dsl.DSL.Reponse");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_9=','
			{
				newLeafNode(otherlv_9, grammarAccess.getQuestionAccess().getCommaKeyword_9_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getQuestionAccess().getReponsesReponseParserRuleCall_9_1_0());
					}
					lv_reponses_10_0=ruleReponse
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getQuestionRule());
						}
						add(
							$current,
							"reponses",
							lv_reponses_10_0,
							"qcm.dsl.DSL.Reponse");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)*
		otherlv_11='}'
		{
			newLeafNode(otherlv_11, grammarAccess.getQuestionAccess().getRightCurlyBracketKeyword_10());
		}
		(
			otherlv_12='etiquette'
			{
				newLeafNode(otherlv_12, grammarAccess.getQuestionAccess().getEtiquetteKeyword_11_0());
			}
			otherlv_13='{'
			{
				newLeafNode(otherlv_13, grammarAccess.getQuestionAccess().getLeftCurlyBracketKeyword_11_1());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getQuestionAccess().getEtiquetteEtiquetteParserRuleCall_11_2_0());
					}
					lv_etiquette_14_0=ruleEtiquette
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getQuestionRule());
						}
						add(
							$current,
							"etiquette",
							lv_etiquette_14_0,
							"qcm.dsl.DSL.Etiquette");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_15=','
				{
					newLeafNode(otherlv_15, grammarAccess.getQuestionAccess().getCommaKeyword_11_3_0());
				}
				(
					(
						{
							newCompositeNode(grammarAccess.getQuestionAccess().getEtiquetteEtiquetteParserRuleCall_11_3_1_0());
						}
						lv_etiquette_16_0=ruleEtiquette
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getQuestionRule());
							}
							add(
								$current,
								"etiquette",
								lv_etiquette_16_0,
								"qcm.dsl.DSL.Etiquette");
							afterParserOrEnumRuleCall();
						}
					)
				)
			)*
			otherlv_17='}'
			{
				newLeafNode(otherlv_17, grammarAccess.getQuestionAccess().getRightCurlyBracketKeyword_11_4());
			}
		)?
		otherlv_18='}'
		{
			newLeafNode(otherlv_18, grammarAccess.getQuestionAccess().getRightCurlyBracketKeyword_12());
		}
	)
;

// Entry rule entryRuleELong
entryRuleELong returns [String current=null]:
	{ newCompositeNode(grammarAccess.getELongRule()); }
	iv_ruleELong=ruleELong
	{ $current=$iv_ruleELong.current.getText(); }
	EOF;

// Rule ELong
ruleELong returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			kw='-'
			{
				$current.merge(kw);
				newLeafNode(kw, grammarAccess.getELongAccess().getHyphenMinusKeyword_0());
			}
		)?
		this_INT_1=RULE_INT
		{
			$current.merge(this_INT_1);
		}
		{
			newLeafNode(this_INT_1, grammarAccess.getELongAccess().getINTTerminalRuleCall_1());
		}
	)
;

// Entry rule entryRuleReponse
entryRuleReponse returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getReponseRule()); }
	iv_ruleReponse=ruleReponse
	{ $current=$iv_ruleReponse.current; }
	EOF;

// Rule Reponse
ruleReponse returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				lv_valide_0_0='valide'
				{
					newLeafNode(lv_valide_0_0, grammarAccess.getReponseAccess().getValideValideKeyword_0_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getReponseRule());
					}
					setWithLastConsumed($current, "valide", lv_valide_0_0 != null, "valide");
				}
			)
		)?
		otherlv_1='Reponse'
		{
			newLeafNode(otherlv_1, grammarAccess.getReponseAccess().getReponseKeyword_1());
		}
		otherlv_2='{'
		{
			newLeafNode(otherlv_2, grammarAccess.getReponseAccess().getLeftCurlyBracketKeyword_2());
		}
		otherlv_3='intitule'
		{
			newLeafNode(otherlv_3, grammarAccess.getReponseAccess().getIntituleKeyword_3());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getReponseAccess().getIntituleEStringParserRuleCall_4_0());
				}
				lv_intitule_4_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getReponseRule());
					}
					set(
						$current,
						"intitule",
						lv_intitule_4_0,
						"qcm.dsl.DSL.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_5='}'
		{
			newLeafNode(otherlv_5, grammarAccess.getReponseAccess().getRightCurlyBracketKeyword_5());
		}
	)
;

// Entry rule entryRuleEtiquette
entryRuleEtiquette returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getEtiquetteRule()); }
	iv_ruleEtiquette=ruleEtiquette
	{ $current=$iv_ruleEtiquette.current; }
	EOF;

// Rule Etiquette
ruleEtiquette returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='Etiquette'
		{
			newLeafNode(otherlv_0, grammarAccess.getEtiquetteAccess().getEtiquetteKeyword_0());
		}
		otherlv_1='{'
		{
			newLeafNode(otherlv_1, grammarAccess.getEtiquetteAccess().getLeftCurlyBracketKeyword_1());
		}
		otherlv_2='categorie'
		{
			newLeafNode(otherlv_2, grammarAccess.getEtiquetteAccess().getCategorieKeyword_2());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getEtiquetteAccess().getCategorieEStringParserRuleCall_3_0());
				}
				lv_categorie_3_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getEtiquetteRule());
					}
					set(
						$current,
						"categorie",
						lv_categorie_3_0,
						"qcm.dsl.DSL.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_4='sousEtiquette'
			{
				newLeafNode(otherlv_4, grammarAccess.getEtiquetteAccess().getSousEtiquetteKeyword_4_0());
			}
			(
				(
					{
						if ($current==null) {
							$current = createModelElement(grammarAccess.getEtiquetteRule());
						}
					}
					{
						newCompositeNode(grammarAccess.getEtiquetteAccess().getSousEtiquetteEtiquetteCrossReference_4_1_0());
					}
					ruleEString
					{
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		otherlv_6='}'
		{
			newLeafNode(otherlv_6, grammarAccess.getEtiquetteAccess().getRightCurlyBracketKeyword_5());
		}
	)
;

RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' .|~(('\\'|'"')))* '"'|'\'' ('\\' .|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;
