/*
 * generated by Xtext 2.37.0
 */
package qcm.dsl.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import qcm.Etiquette;
import qcm.QcmPackage;
import qcm.Question;
import qcm.Questionnaire;
import qcm.Reponse;
import qcm.dsl.services.DSLGrammarAccess;

@SuppressWarnings("all")
public class DSLSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private DSLGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == QcmPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case QcmPackage.ETIQUETTE:
				sequence_Etiquette(context, (Etiquette) semanticObject); 
				return; 
			case QcmPackage.QUESTION:
				sequence_Question(context, (Question) semanticObject); 
				return; 
			case QcmPackage.QUESTIONNAIRE:
				sequence_Questionnaire(context, (Questionnaire) semanticObject); 
				return; 
			case QcmPackage.REPONSE:
				sequence_Reponse(context, (Reponse) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Etiquette returns Etiquette
	 *
	 * Constraint:
	 *     (categorie=EString sousEtiquette=[Etiquette|EString]?)
	 * </pre>
	 */
	protected void sequence_Etiquette(ISerializationContext context, Etiquette semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Question returns Question
	 *
	 * Constraint:
	 *     (
	 *         reponseUnique?='reponseUnique' 
	 *         intitule=EString 
	 *         difficulte=ELong 
	 *         questionSuivante=[Question|EString]? 
	 *         reponses+=Reponse 
	 *         reponses+=Reponse* 
	 *         (etiquette+=Etiquette etiquette+=Etiquette*)?
	 *     )
	 * </pre>
	 */
	protected void sequence_Question(ISerializationContext context, Question semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Questionnaire returns Questionnaire
	 *
	 * Constraint:
	 *     (melange?='melange'? titre=EString retourArriere=EBoolean? possede+=Question possede+=Question*)
	 * </pre>
	 */
	protected void sequence_Questionnaire(ISerializationContext context, Questionnaire semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Reponse returns Reponse
	 *
	 * Constraint:
	 *     (valide?='valide'? intitule=EString)
	 * </pre>
	 */
	protected void sequence_Reponse(ISerializationContext context, Reponse semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
