/*
 * generated by Xtext 2.37.0
 */
grammar InternalDSL;

options {
	superClass=AbstractInternalContentAssistParser;
}

@lexer::header {
package qcm.dsl.ide.contentassist.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.Lexer;
}

@parser::header {
package qcm.dsl.ide.contentassist.antlr.internal;

import java.io.InputStream;
import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.DFA;
import qcm.dsl.services.DSLGrammarAccess;

}
@parser::members {
	private DSLGrammarAccess grammarAccess;

	public void setGrammarAccess(DSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}

	@Override
	protected Grammar getGrammar() {
		return grammarAccess.getGrammar();
	}

	@Override
	protected String getValueForTokenName(String tokenName) {
		return tokenName;
	}
}

// Entry rule entryRuleQuestionnaire
entryRuleQuestionnaire
:
{ before(grammarAccess.getQuestionnaireRule()); }
	 ruleQuestionnaire
{ after(grammarAccess.getQuestionnaireRule()); } 
	 EOF 
;

// Rule Questionnaire
ruleQuestionnaire 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getQuestionnaireAccess().getGroup()); }
		(rule__Questionnaire__Group__0)
		{ after(grammarAccess.getQuestionnaireAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleEString
entryRuleEString
:
{ before(grammarAccess.getEStringRule()); }
	 ruleEString
{ after(grammarAccess.getEStringRule()); } 
	 EOF 
;

// Rule EString
ruleEString 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getEStringAccess().getAlternatives()); }
		(rule__EString__Alternatives)
		{ after(grammarAccess.getEStringAccess().getAlternatives()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleEBoolean
entryRuleEBoolean
:
{ before(grammarAccess.getEBooleanRule()); }
	 ruleEBoolean
{ after(grammarAccess.getEBooleanRule()); } 
	 EOF 
;

// Rule EBoolean
ruleEBoolean 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getEBooleanAccess().getAlternatives()); }
		(rule__EBoolean__Alternatives)
		{ after(grammarAccess.getEBooleanAccess().getAlternatives()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleQuestion
entryRuleQuestion
:
{ before(grammarAccess.getQuestionRule()); }
	 ruleQuestion
{ after(grammarAccess.getQuestionRule()); } 
	 EOF 
;

// Rule Question
ruleQuestion 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getQuestionAccess().getGroup()); }
		(rule__Question__Group__0)
		{ after(grammarAccess.getQuestionAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleELong
entryRuleELong
:
{ before(grammarAccess.getELongRule()); }
	 ruleELong
{ after(grammarAccess.getELongRule()); } 
	 EOF 
;

// Rule ELong
ruleELong 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getELongAccess().getGroup()); }
		(rule__ELong__Group__0)
		{ after(grammarAccess.getELongAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleReponse
entryRuleReponse
:
{ before(grammarAccess.getReponseRule()); }
	 ruleReponse
{ after(grammarAccess.getReponseRule()); } 
	 EOF 
;

// Rule Reponse
ruleReponse 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getReponseAccess().getGroup()); }
		(rule__Reponse__Group__0)
		{ after(grammarAccess.getReponseAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleEtiquette
entryRuleEtiquette
:
{ before(grammarAccess.getEtiquetteRule()); }
	 ruleEtiquette
{ after(grammarAccess.getEtiquetteRule()); } 
	 EOF 
;

// Rule Etiquette
ruleEtiquette 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getEtiquetteAccess().getGroup()); }
		(rule__Etiquette__Group__0)
		{ after(grammarAccess.getEtiquetteAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__EString__Alternatives
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEStringAccess().getSTRINGTerminalRuleCall_0()); }
		RULE_STRING
		{ after(grammarAccess.getEStringAccess().getSTRINGTerminalRuleCall_0()); }
	)
	|
	(
		{ before(grammarAccess.getEStringAccess().getIDTerminalRuleCall_1()); }
		RULE_ID
		{ after(grammarAccess.getEStringAccess().getIDTerminalRuleCall_1()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__EBoolean__Alternatives
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEBooleanAccess().getTrueKeyword_0()); }
		'true'
		{ after(grammarAccess.getEBooleanAccess().getTrueKeyword_0()); }
	)
	|
	(
		{ before(grammarAccess.getEBooleanAccess().getFalseKeyword_1()); }
		'false'
		{ after(grammarAccess.getEBooleanAccess().getFalseKeyword_1()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Questionnaire__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Questionnaire__Group__0__Impl
	rule__Questionnaire__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Questionnaire__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionnaireAccess().getMelangeAssignment_0()); }
	(rule__Questionnaire__MelangeAssignment_0)?
	{ after(grammarAccess.getQuestionnaireAccess().getMelangeAssignment_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Questionnaire__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Questionnaire__Group__1__Impl
	rule__Questionnaire__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Questionnaire__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionnaireAccess().getQuestionnaireKeyword_1()); }
	'Questionnaire'
	{ after(grammarAccess.getQuestionnaireAccess().getQuestionnaireKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Questionnaire__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Questionnaire__Group__2__Impl
	rule__Questionnaire__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Questionnaire__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionnaireAccess().getLeftCurlyBracketKeyword_2()); }
	'{'
	{ after(grammarAccess.getQuestionnaireAccess().getLeftCurlyBracketKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Questionnaire__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Questionnaire__Group__3__Impl
	rule__Questionnaire__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Questionnaire__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionnaireAccess().getTitreKeyword_3()); }
	'titre'
	{ after(grammarAccess.getQuestionnaireAccess().getTitreKeyword_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Questionnaire__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Questionnaire__Group__4__Impl
	rule__Questionnaire__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__Questionnaire__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionnaireAccess().getTitreAssignment_4()); }
	(rule__Questionnaire__TitreAssignment_4)
	{ after(grammarAccess.getQuestionnaireAccess().getTitreAssignment_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Questionnaire__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Questionnaire__Group__5__Impl
	rule__Questionnaire__Group__6
;
finally {
	restoreStackSize(stackSize);
}

rule__Questionnaire__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionnaireAccess().getGroup_5()); }
	(rule__Questionnaire__Group_5__0)?
	{ after(grammarAccess.getQuestionnaireAccess().getGroup_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Questionnaire__Group__6
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Questionnaire__Group__6__Impl
	rule__Questionnaire__Group__7
;
finally {
	restoreStackSize(stackSize);
}

rule__Questionnaire__Group__6__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionnaireAccess().getPossedeKeyword_6()); }
	'possede'
	{ after(grammarAccess.getQuestionnaireAccess().getPossedeKeyword_6()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Questionnaire__Group__7
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Questionnaire__Group__7__Impl
	rule__Questionnaire__Group__8
;
finally {
	restoreStackSize(stackSize);
}

rule__Questionnaire__Group__7__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionnaireAccess().getLeftCurlyBracketKeyword_7()); }
	'{'
	{ after(grammarAccess.getQuestionnaireAccess().getLeftCurlyBracketKeyword_7()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Questionnaire__Group__8
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Questionnaire__Group__8__Impl
	rule__Questionnaire__Group__9
;
finally {
	restoreStackSize(stackSize);
}

rule__Questionnaire__Group__8__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionnaireAccess().getPossedeAssignment_8()); }
	(rule__Questionnaire__PossedeAssignment_8)
	{ after(grammarAccess.getQuestionnaireAccess().getPossedeAssignment_8()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Questionnaire__Group__9
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Questionnaire__Group__9__Impl
	rule__Questionnaire__Group__10
;
finally {
	restoreStackSize(stackSize);
}

rule__Questionnaire__Group__9__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionnaireAccess().getGroup_9()); }
	(rule__Questionnaire__Group_9__0)*
	{ after(grammarAccess.getQuestionnaireAccess().getGroup_9()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Questionnaire__Group__10
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Questionnaire__Group__10__Impl
	rule__Questionnaire__Group__11
;
finally {
	restoreStackSize(stackSize);
}

rule__Questionnaire__Group__10__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionnaireAccess().getRightCurlyBracketKeyword_10()); }
	'}'
	{ after(grammarAccess.getQuestionnaireAccess().getRightCurlyBracketKeyword_10()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Questionnaire__Group__11
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Questionnaire__Group__11__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Questionnaire__Group__11__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionnaireAccess().getRightCurlyBracketKeyword_11()); }
	'}'
	{ after(grammarAccess.getQuestionnaireAccess().getRightCurlyBracketKeyword_11()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Questionnaire__Group_5__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Questionnaire__Group_5__0__Impl
	rule__Questionnaire__Group_5__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Questionnaire__Group_5__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionnaireAccess().getRetourArriereKeyword_5_0()); }
	'retourArriere'
	{ after(grammarAccess.getQuestionnaireAccess().getRetourArriereKeyword_5_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Questionnaire__Group_5__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Questionnaire__Group_5__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Questionnaire__Group_5__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionnaireAccess().getRetourArriereAssignment_5_1()); }
	(rule__Questionnaire__RetourArriereAssignment_5_1)
	{ after(grammarAccess.getQuestionnaireAccess().getRetourArriereAssignment_5_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Questionnaire__Group_9__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Questionnaire__Group_9__0__Impl
	rule__Questionnaire__Group_9__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Questionnaire__Group_9__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionnaireAccess().getCommaKeyword_9_0()); }
	','
	{ after(grammarAccess.getQuestionnaireAccess().getCommaKeyword_9_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Questionnaire__Group_9__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Questionnaire__Group_9__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Questionnaire__Group_9__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionnaireAccess().getPossedeAssignment_9_1()); }
	(rule__Questionnaire__PossedeAssignment_9_1)
	{ after(grammarAccess.getQuestionnaireAccess().getPossedeAssignment_9_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Question__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Question__Group__0__Impl
	rule__Question__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionAccess().getReponseUniqueAssignment_0()); }
	(rule__Question__ReponseUniqueAssignment_0)
	{ after(grammarAccess.getQuestionAccess().getReponseUniqueAssignment_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Question__Group__1__Impl
	rule__Question__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionAccess().getQuestionKeyword_1()); }
	'Question'
	{ after(grammarAccess.getQuestionAccess().getQuestionKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Question__Group__2__Impl
	rule__Question__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionAccess().getLeftCurlyBracketKeyword_2()); }
	'{'
	{ after(grammarAccess.getQuestionAccess().getLeftCurlyBracketKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Question__Group__3__Impl
	rule__Question__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionAccess().getIntituleKeyword_3()); }
	'intitule'
	{ after(grammarAccess.getQuestionAccess().getIntituleKeyword_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Question__Group__4__Impl
	rule__Question__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionAccess().getIntituleAssignment_4()); }
	(rule__Question__IntituleAssignment_4)
	{ after(grammarAccess.getQuestionAccess().getIntituleAssignment_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Question__Group__5__Impl
	rule__Question__Group__6
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionAccess().getDifficulteKeyword_5()); }
	'difficulte'
	{ after(grammarAccess.getQuestionAccess().getDifficulteKeyword_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__Group__6
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Question__Group__6__Impl
	rule__Question__Group__7
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__Group__6__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionAccess().getDifficulteAssignment_6()); }
	(rule__Question__DifficulteAssignment_6)
	{ after(grammarAccess.getQuestionAccess().getDifficulteAssignment_6()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__Group__7
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Question__Group__7__Impl
	rule__Question__Group__8
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__Group__7__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionAccess().getGroup_7()); }
	(rule__Question__Group_7__0)?
	{ after(grammarAccess.getQuestionAccess().getGroup_7()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__Group__8
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Question__Group__8__Impl
	rule__Question__Group__9
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__Group__8__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionAccess().getReponsesKeyword_8()); }
	'reponses'
	{ after(grammarAccess.getQuestionAccess().getReponsesKeyword_8()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__Group__9
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Question__Group__9__Impl
	rule__Question__Group__10
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__Group__9__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionAccess().getLeftCurlyBracketKeyword_9()); }
	'{'
	{ after(grammarAccess.getQuestionAccess().getLeftCurlyBracketKeyword_9()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__Group__10
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Question__Group__10__Impl
	rule__Question__Group__11
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__Group__10__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionAccess().getReponsesAssignment_10()); }
	(rule__Question__ReponsesAssignment_10)
	{ after(grammarAccess.getQuestionAccess().getReponsesAssignment_10()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__Group__11
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Question__Group__11__Impl
	rule__Question__Group__12
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__Group__11__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionAccess().getGroup_11()); }
	(rule__Question__Group_11__0)*
	{ after(grammarAccess.getQuestionAccess().getGroup_11()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__Group__12
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Question__Group__12__Impl
	rule__Question__Group__13
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__Group__12__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionAccess().getRightCurlyBracketKeyword_12()); }
	'}'
	{ after(grammarAccess.getQuestionAccess().getRightCurlyBracketKeyword_12()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__Group__13
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Question__Group__13__Impl
	rule__Question__Group__14
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__Group__13__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionAccess().getGroup_13()); }
	(rule__Question__Group_13__0)?
	{ after(grammarAccess.getQuestionAccess().getGroup_13()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__Group__14
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Question__Group__14__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__Group__14__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionAccess().getRightCurlyBracketKeyword_14()); }
	'}'
	{ after(grammarAccess.getQuestionAccess().getRightCurlyBracketKeyword_14()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Question__Group_7__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Question__Group_7__0__Impl
	rule__Question__Group_7__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__Group_7__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionAccess().getQuestionSuivanteKeyword_7_0()); }
	'questionSuivante'
	{ after(grammarAccess.getQuestionAccess().getQuestionSuivanteKeyword_7_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__Group_7__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Question__Group_7__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__Group_7__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionAccess().getQuestionSuivanteAssignment_7_1()); }
	(rule__Question__QuestionSuivanteAssignment_7_1)
	{ after(grammarAccess.getQuestionAccess().getQuestionSuivanteAssignment_7_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Question__Group_11__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Question__Group_11__0__Impl
	rule__Question__Group_11__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__Group_11__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionAccess().getCommaKeyword_11_0()); }
	','
	{ after(grammarAccess.getQuestionAccess().getCommaKeyword_11_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__Group_11__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Question__Group_11__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__Group_11__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionAccess().getReponsesAssignment_11_1()); }
	(rule__Question__ReponsesAssignment_11_1)
	{ after(grammarAccess.getQuestionAccess().getReponsesAssignment_11_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Question__Group_13__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Question__Group_13__0__Impl
	rule__Question__Group_13__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__Group_13__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionAccess().getEtiquetteKeyword_13_0()); }
	'etiquette'
	{ after(grammarAccess.getQuestionAccess().getEtiquetteKeyword_13_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__Group_13__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Question__Group_13__1__Impl
	rule__Question__Group_13__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__Group_13__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionAccess().getLeftCurlyBracketKeyword_13_1()); }
	'{'
	{ after(grammarAccess.getQuestionAccess().getLeftCurlyBracketKeyword_13_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__Group_13__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Question__Group_13__2__Impl
	rule__Question__Group_13__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__Group_13__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionAccess().getEtiquetteAssignment_13_2()); }
	(rule__Question__EtiquetteAssignment_13_2)
	{ after(grammarAccess.getQuestionAccess().getEtiquetteAssignment_13_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__Group_13__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Question__Group_13__3__Impl
	rule__Question__Group_13__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__Group_13__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionAccess().getGroup_13_3()); }
	(rule__Question__Group_13_3__0)*
	{ after(grammarAccess.getQuestionAccess().getGroup_13_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__Group_13__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Question__Group_13__4__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__Group_13__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionAccess().getRightCurlyBracketKeyword_13_4()); }
	'}'
	{ after(grammarAccess.getQuestionAccess().getRightCurlyBracketKeyword_13_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Question__Group_13_3__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Question__Group_13_3__0__Impl
	rule__Question__Group_13_3__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__Group_13_3__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionAccess().getCommaKeyword_13_3_0()); }
	','
	{ after(grammarAccess.getQuestionAccess().getCommaKeyword_13_3_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__Group_13_3__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Question__Group_13_3__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__Group_13_3__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionAccess().getEtiquetteAssignment_13_3_1()); }
	(rule__Question__EtiquetteAssignment_13_3_1)
	{ after(grammarAccess.getQuestionAccess().getEtiquetteAssignment_13_3_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__ELong__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__ELong__Group__0__Impl
	rule__ELong__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__ELong__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getELongAccess().getHyphenMinusKeyword_0()); }
	('-')?
	{ after(grammarAccess.getELongAccess().getHyphenMinusKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__ELong__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__ELong__Group__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__ELong__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getELongAccess().getINTTerminalRuleCall_1()); }
	RULE_INT
	{ after(grammarAccess.getELongAccess().getINTTerminalRuleCall_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Reponse__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Reponse__Group__0__Impl
	rule__Reponse__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Reponse__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getReponseAccess().getValideAssignment_0()); }
	(rule__Reponse__ValideAssignment_0)?
	{ after(grammarAccess.getReponseAccess().getValideAssignment_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Reponse__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Reponse__Group__1__Impl
	rule__Reponse__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Reponse__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getReponseAccess().getReponseKeyword_1()); }
	'Reponse'
	{ after(grammarAccess.getReponseAccess().getReponseKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Reponse__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Reponse__Group__2__Impl
	rule__Reponse__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Reponse__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getReponseAccess().getLeftCurlyBracketKeyword_2()); }
	'{'
	{ after(grammarAccess.getReponseAccess().getLeftCurlyBracketKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Reponse__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Reponse__Group__3__Impl
	rule__Reponse__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Reponse__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getReponseAccess().getIntituleKeyword_3()); }
	'intitule'
	{ after(grammarAccess.getReponseAccess().getIntituleKeyword_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Reponse__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Reponse__Group__4__Impl
	rule__Reponse__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__Reponse__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getReponseAccess().getIntituleAssignment_4()); }
	(rule__Reponse__IntituleAssignment_4)
	{ after(grammarAccess.getReponseAccess().getIntituleAssignment_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Reponse__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Reponse__Group__5__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Reponse__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getReponseAccess().getRightCurlyBracketKeyword_5()); }
	'}'
	{ after(grammarAccess.getReponseAccess().getRightCurlyBracketKeyword_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Etiquette__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Etiquette__Group__0__Impl
	rule__Etiquette__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Etiquette__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEtiquetteAccess().getEtiquetteKeyword_0()); }
	'Etiquette'
	{ after(grammarAccess.getEtiquetteAccess().getEtiquetteKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Etiquette__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Etiquette__Group__1__Impl
	rule__Etiquette__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Etiquette__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEtiquetteAccess().getLeftCurlyBracketKeyword_1()); }
	'{'
	{ after(grammarAccess.getEtiquetteAccess().getLeftCurlyBracketKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Etiquette__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Etiquette__Group__2__Impl
	rule__Etiquette__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Etiquette__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEtiquetteAccess().getCategorieKeyword_2()); }
	'categorie'
	{ after(grammarAccess.getEtiquetteAccess().getCategorieKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Etiquette__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Etiquette__Group__3__Impl
	rule__Etiquette__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Etiquette__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEtiquetteAccess().getCategorieAssignment_3()); }
	(rule__Etiquette__CategorieAssignment_3)
	{ after(grammarAccess.getEtiquetteAccess().getCategorieAssignment_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Etiquette__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Etiquette__Group__4__Impl
	rule__Etiquette__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__Etiquette__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEtiquetteAccess().getGroup_4()); }
	(rule__Etiquette__Group_4__0)?
	{ after(grammarAccess.getEtiquetteAccess().getGroup_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Etiquette__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Etiquette__Group__5__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Etiquette__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEtiquetteAccess().getRightCurlyBracketKeyword_5()); }
	'}'
	{ after(grammarAccess.getEtiquetteAccess().getRightCurlyBracketKeyword_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Etiquette__Group_4__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Etiquette__Group_4__0__Impl
	rule__Etiquette__Group_4__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Etiquette__Group_4__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEtiquetteAccess().getSousEtiquetteKeyword_4_0()); }
	'sousEtiquette'
	{ after(grammarAccess.getEtiquetteAccess().getSousEtiquetteKeyword_4_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Etiquette__Group_4__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Etiquette__Group_4__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Etiquette__Group_4__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEtiquetteAccess().getSousEtiquetteAssignment_4_1()); }
	(rule__Etiquette__SousEtiquetteAssignment_4_1)
	{ after(grammarAccess.getEtiquetteAccess().getSousEtiquetteAssignment_4_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Questionnaire__MelangeAssignment_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getQuestionnaireAccess().getMelangeMelangeKeyword_0_0()); }
		(
			{ before(grammarAccess.getQuestionnaireAccess().getMelangeMelangeKeyword_0_0()); }
			'melange'
			{ after(grammarAccess.getQuestionnaireAccess().getMelangeMelangeKeyword_0_0()); }
		)
		{ after(grammarAccess.getQuestionnaireAccess().getMelangeMelangeKeyword_0_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Questionnaire__TitreAssignment_4
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getQuestionnaireAccess().getTitreEStringParserRuleCall_4_0()); }
		ruleEString
		{ after(grammarAccess.getQuestionnaireAccess().getTitreEStringParserRuleCall_4_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Questionnaire__RetourArriereAssignment_5_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getQuestionnaireAccess().getRetourArriereEBooleanParserRuleCall_5_1_0()); }
		ruleEBoolean
		{ after(grammarAccess.getQuestionnaireAccess().getRetourArriereEBooleanParserRuleCall_5_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Questionnaire__PossedeAssignment_8
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getQuestionnaireAccess().getPossedeQuestionParserRuleCall_8_0()); }
		ruleQuestion
		{ after(grammarAccess.getQuestionnaireAccess().getPossedeQuestionParserRuleCall_8_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Questionnaire__PossedeAssignment_9_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getQuestionnaireAccess().getPossedeQuestionParserRuleCall_9_1_0()); }
		ruleQuestion
		{ after(grammarAccess.getQuestionnaireAccess().getPossedeQuestionParserRuleCall_9_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__ReponseUniqueAssignment_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getQuestionAccess().getReponseUniqueReponseUniqueKeyword_0_0()); }
		(
			{ before(grammarAccess.getQuestionAccess().getReponseUniqueReponseUniqueKeyword_0_0()); }
			'reponseUnique'
			{ after(grammarAccess.getQuestionAccess().getReponseUniqueReponseUniqueKeyword_0_0()); }
		)
		{ after(grammarAccess.getQuestionAccess().getReponseUniqueReponseUniqueKeyword_0_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__IntituleAssignment_4
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getQuestionAccess().getIntituleEStringParserRuleCall_4_0()); }
		ruleEString
		{ after(grammarAccess.getQuestionAccess().getIntituleEStringParserRuleCall_4_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__DifficulteAssignment_6
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getQuestionAccess().getDifficulteELongParserRuleCall_6_0()); }
		ruleELong
		{ after(grammarAccess.getQuestionAccess().getDifficulteELongParserRuleCall_6_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__QuestionSuivanteAssignment_7_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getQuestionAccess().getQuestionSuivanteQuestionCrossReference_7_1_0()); }
		(
			{ before(grammarAccess.getQuestionAccess().getQuestionSuivanteQuestionEStringParserRuleCall_7_1_0_1()); }
			ruleEString
			{ after(grammarAccess.getQuestionAccess().getQuestionSuivanteQuestionEStringParserRuleCall_7_1_0_1()); }
		)
		{ after(grammarAccess.getQuestionAccess().getQuestionSuivanteQuestionCrossReference_7_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__ReponsesAssignment_10
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getQuestionAccess().getReponsesReponseParserRuleCall_10_0()); }
		ruleReponse
		{ after(grammarAccess.getQuestionAccess().getReponsesReponseParserRuleCall_10_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__ReponsesAssignment_11_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getQuestionAccess().getReponsesReponseParserRuleCall_11_1_0()); }
		ruleReponse
		{ after(grammarAccess.getQuestionAccess().getReponsesReponseParserRuleCall_11_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__EtiquetteAssignment_13_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getQuestionAccess().getEtiquetteEtiquetteParserRuleCall_13_2_0()); }
		ruleEtiquette
		{ after(grammarAccess.getQuestionAccess().getEtiquetteEtiquetteParserRuleCall_13_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Question__EtiquetteAssignment_13_3_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getQuestionAccess().getEtiquetteEtiquetteParserRuleCall_13_3_1_0()); }
		ruleEtiquette
		{ after(grammarAccess.getQuestionAccess().getEtiquetteEtiquetteParserRuleCall_13_3_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Reponse__ValideAssignment_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getReponseAccess().getValideValideKeyword_0_0()); }
		(
			{ before(grammarAccess.getReponseAccess().getValideValideKeyword_0_0()); }
			'valide'
			{ after(grammarAccess.getReponseAccess().getValideValideKeyword_0_0()); }
		)
		{ after(grammarAccess.getReponseAccess().getValideValideKeyword_0_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Reponse__IntituleAssignment_4
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getReponseAccess().getIntituleEStringParserRuleCall_4_0()); }
		ruleEString
		{ after(grammarAccess.getReponseAccess().getIntituleEStringParserRuleCall_4_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Etiquette__CategorieAssignment_3
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEtiquetteAccess().getCategorieEStringParserRuleCall_3_0()); }
		ruleEString
		{ after(grammarAccess.getEtiquetteAccess().getCategorieEStringParserRuleCall_3_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Etiquette__SousEtiquetteAssignment_4_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEtiquetteAccess().getSousEtiquetteEtiquetteCrossReference_4_1_0()); }
		(
			{ before(grammarAccess.getEtiquetteAccess().getSousEtiquetteEtiquetteEStringParserRuleCall_4_1_0_1()); }
			ruleEString
			{ after(grammarAccess.getEtiquetteAccess().getSousEtiquetteEtiquetteEStringParserRuleCall_4_1_0_1()); }
		)
		{ after(grammarAccess.getEtiquetteAccess().getSousEtiquetteEtiquetteCrossReference_4_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' .|~(('\\'|'"')))* '"'|'\'' ('\\' .|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;
