/**
 * generated by Xtext 2.37.0
 */
package qcm.dsl.formatting2;

import com.google.inject.Inject;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.XbaseGenerated;
import qcm.Etiquette;
import qcm.Question;
import qcm.Questionnaire;
import qcm.Reponse;
import qcm.dsl.services.DSLGrammarAccess;

@SuppressWarnings("all")
public class DSLFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private DSLGrammarAccess _dSLGrammarAccess;

  protected void _format(final Questionnaire questionnaire, @Extension final IFormattableDocument document) {
    EList<Question> _possede = questionnaire.getPossede();
    for (final Question question : _possede) {
      document.<Question>format(question);
    }
  }

  protected void _format(final Question question, @Extension final IFormattableDocument document) {
    EList<Reponse> _reponses = question.getReponses();
    for (final Reponse reponse : _reponses) {
      document.<Reponse>format(reponse);
    }
    EList<Etiquette> _etiquette = question.getEtiquette();
    for (final Etiquette etiquette : _etiquette) {
      document.<Etiquette>format(etiquette);
    }
  }

  @XbaseGenerated
  public void format(final Object question, final IFormattableDocument document) {
    if (question instanceof XtextResource) {
      _format((XtextResource)question, document);
      return;
    } else if (question instanceof Question) {
      _format((Question)question, document);
      return;
    } else if (question instanceof Questionnaire) {
      _format((Questionnaire)question, document);
      return;
    } else if (question instanceof EObject) {
      _format((EObject)question, document);
      return;
    } else if (question == null) {
      _format((Void)null, document);
      return;
    } else if (question != null) {
      _format(question, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(question, document).toString());
    }
  }
}
