/*
 * generated by Xtext 2.37.0
 */
package qcm.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class DSLUiModule extends AbstractDSLUiModule {

	public DSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
